//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 09:04:38 PM GMT 
//


package rebelo.reports.core.parse.pojo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rebelo.reports.core.parse.pojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Jsonhttps_QNAME = new QName("urn:rebelo.reports.core.parse.pojo", "jsonhttps");
    private final static QName _Jsonhttp_QNAME = new QName("urn:rebelo.reports.core.parse.pojo", "jsonhttp");
    private final static QName _Xmlhttp_QNAME = new QName("urn:rebelo.reports.core.parse.pojo", "xmlhttp");
    private final static QName _Xmlhttps_QNAME = new QName("urn:rebelo.reports.core.parse.pojo", "xmlhttps");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rebelo.reports.core.parse.pojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rreport }
     * 
     */
    public Rreport createRreport() {
        return new Rreport();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Sign }
     * 
     */
    public Sign createSign() {
        return new Sign();
    }

    /**
     * Create an instance of {@link Sign.Rectangle }
     * 
     */
    public Sign.Rectangle createSignRectangle() {
        return new Sign.Rectangle();
    }

    /**
     * Create an instance of {@link Sign.Keystore }
     * 
     */
    public Sign.Keystore createSignKeystore() {
        return new Sign.Keystore();
    }

    /**
     * Create an instance of {@link Xlsx }
     * 
     */
    public Xlsx createXlsx() {
        return new Xlsx();
    }

    /**
     * Create an instance of {@link Jsonserver }
     * 
     */
    public Jsonserver createJsonserver() {
        return new Jsonserver();
    }

    /**
     * Create an instance of {@link Rtf }
     * 
     */
    public Rtf createRtf() {
        return new Rtf();
    }

    /**
     * Create an instance of {@link Csv }
     * 
     */
    public Csv createCsv() {
        return new Csv();
    }

    /**
     * Create an instance of {@link Docx }
     * 
     */
    public Docx createDocx() {
        return new Docx();
    }

    /**
     * Create an instance of {@link Pptx }
     * 
     */
    public Pptx createPptx() {
        return new Pptx();
    }

    /**
     * Create an instance of {@link Xmlserver }
     * 
     */
    public Xmlserver createXmlserver() {
        return new Xmlserver();
    }

    /**
     * Create an instance of {@link Database }
     * 
     */
    public Database createDatabase() {
        return new Database();
    }

    /**
     * Create an instance of {@link Print }
     * 
     */
    public Print createPrint() {
        return new Print();
    }

    /**
     * Create an instance of {@link Pdf }
     * 
     */
    public Pdf createPdf() {
        return new Pdf();
    }

    /**
     * Create an instance of {@link Rreport.Jasperfile }
     * 
     */
    public Rreport.Jasperfile createRreportJasperfile() {
        return new Rreport.Jasperfile();
    }

    /**
     * Create an instance of {@link Rreport.Reporttype }
     * 
     */
    public Rreport.Reporttype createRreportReporttype() {
        return new Rreport.Reporttype();
    }

    /**
     * Create an instance of {@link Rreport.Datasource }
     * 
     */
    public Rreport.Datasource createRreportDatasource() {
        return new Rreport.Datasource();
    }

    /**
     * Create an instance of {@link Rreport.Parameters }
     * 
     */
    public Rreport.Parameters createRreportParameters() {
        return new Rreport.Parameters();
    }

    /**
     * Create an instance of {@link Xml }
     * 
     */
    public Xml createXml() {
        return new Xml();
    }

    /**
     * Create an instance of {@link Parameter.Value }
     * 
     */
    public Parameter.Value createParameterValue() {
        return new Parameter.Value();
    }

    /**
     * Create an instance of {@link Json }
     * 
     */
    public Json createJson() {
        return new Json();
    }

    /**
     * Create an instance of {@link Html }
     * 
     */
    public Html createHtml() {
        return new Html();
    }

    /**
     * Create an instance of {@link Text }
     * 
     */
    public Text createText() {
        return new Text();
    }

    /**
     * Create an instance of {@link rebelo.reports.core.parse.pojo.Parameters }
     * 
     */
    public rebelo.reports.core.parse.pojo.Parameters createParameters() {
        return new rebelo.reports.core.parse.pojo.Parameters();
    }

    /**
     * Create an instance of {@link Xls }
     * 
     */
    public Xls createXls() {
        return new Xls();
    }

    /**
     * Create an instance of {@link Odt }
     * 
     */
    public Odt createOdt() {
        return new Odt();
    }

    /**
     * Create an instance of {@link Ods }
     * 
     */
    public Ods createOds() {
        return new Ods();
    }

    /**
     * Create an instance of {@link Sign.Rectangle.Position }
     * 
     */
    public Sign.Rectangle.Position createSignRectanglePosition() {
        return new Sign.Rectangle.Position();
    }

    /**
     * Create an instance of {@link Sign.Keystore.Certificate }
     * 
     */
    public Sign.Keystore.Certificate createSignKeystoreCertificate() {
        return new Sign.Keystore.Certificate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Jsonserver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:rebelo.reports.core.parse.pojo", name = "jsonhttps")
    public JAXBElement<Jsonserver> createJsonhttps(Jsonserver value) {
        return new JAXBElement<Jsonserver>(_Jsonhttps_QNAME, Jsonserver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Jsonserver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:rebelo.reports.core.parse.pojo", name = "jsonhttp")
    public JAXBElement<Jsonserver> createJsonhttp(Jsonserver value) {
        return new JAXBElement<Jsonserver>(_Jsonhttp_QNAME, Jsonserver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xmlserver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:rebelo.reports.core.parse.pojo", name = "xmlhttp")
    public JAXBElement<Xmlserver> createXmlhttp(Xmlserver value) {
        return new JAXBElement<Xmlserver>(_Xmlhttp_QNAME, Xmlserver.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Xmlserver }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:rebelo.reports.core.parse.pojo", name = "xmlhttps")
    public JAXBElement<Xmlserver> createXmlhttps(Xmlserver value) {
        return new JAXBElement<Xmlserver>(_Xmlhttps_QNAME, Xmlserver.class, null, value);
    }

}
