//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.12 at 09:04:38 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:rebelo.reports.core.parse.pojo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rebelo.reports.core.parse.pojo;
