//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 08:47:55 PM GMT 
//


package rebelo.reports.core.parse.pojo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="jasperfile" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reporttype">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}pdf"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}csv"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}html"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xls"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xml"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}rtf"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}text"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}pptx"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xlsx"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}docx"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}odt"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}ods"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}json"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}print"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="datasource">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}database"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}jsonhttp"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}jsonhttps"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xmlhttp"/>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xmlhttps"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="parameters" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{urn:rebelo.reports.core.parse.pojo}parameter" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "jasperfile",
    "reporttype",
    "datasource",
    "parameters"
})
@XmlRootElement(name = "rreport")
public class Rreport {

    @XmlElement(required = true)
    protected String jasperfile;
    @XmlElement(required = true)
    protected Rreport.Reporttype reporttype;
    @XmlElement(required = true)
    protected Rreport.Datasource datasource;
    protected Rreport.Parameters parameters;

    /**
     * Gets the value of the jasperfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJasperfile() {
        return jasperfile;
    }

    /**
     * Sets the value of the jasperfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJasperfile(String value) {
        this.jasperfile = value;
    }

    /**
     * Gets the value of the reporttype property.
     * 
     * @return
     *     possible object is
     *     {@link Rreport.Reporttype }
     *     
     */
    public Rreport.Reporttype getReporttype() {
        return reporttype;
    }

    /**
     * Sets the value of the reporttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rreport.Reporttype }
     *     
     */
    public void setReporttype(Rreport.Reporttype value) {
        this.reporttype = value;
    }

    /**
     * Gets the value of the datasource property.
     * 
     * @return
     *     possible object is
     *     {@link Rreport.Datasource }
     *     
     */
    public Rreport.Datasource getDatasource() {
        return datasource;
    }

    /**
     * Sets the value of the datasource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rreport.Datasource }
     *     
     */
    public void setDatasource(Rreport.Datasource value) {
        this.datasource = value;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Rreport.Parameters }
     *     
     */
    public Rreport.Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rreport.Parameters }
     *     
     */
    public void setParameters(Rreport.Parameters value) {
        this.parameters = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}database"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}jsonhttp"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}jsonhttps"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xmlhttp"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xmlhttps"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "database",
        "jsonhttp",
        "jsonhttps",
        "xmlhttp",
        "xmlhttps"
    })
    public static class Datasource {

        protected Database database;
        protected Jsonserver jsonhttp;
        protected Jsonserver jsonhttps;
        protected Xmlserver xmlhttp;
        protected Xmlserver xmlhttps;

        /**
         * Gets the value of the database property.
         * 
         * @return
         *     possible object is
         *     {@link Database }
         *     
         */
        public Database getDatabase() {
            return database;
        }

        /**
         * Sets the value of the database property.
         * 
         * @param value
         *     allowed object is
         *     {@link Database }
         *     
         */
        public void setDatabase(Database value) {
            this.database = value;
        }

        /**
         * Gets the value of the jsonhttp property.
         * 
         * @return
         *     possible object is
         *     {@link Jsonserver }
         *     
         */
        public Jsonserver getJsonhttp() {
            return jsonhttp;
        }

        /**
         * Sets the value of the jsonhttp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Jsonserver }
         *     
         */
        public void setJsonhttp(Jsonserver value) {
            this.jsonhttp = value;
        }

        /**
         * Gets the value of the jsonhttps property.
         * 
         * @return
         *     possible object is
         *     {@link Jsonserver }
         *     
         */
        public Jsonserver getJsonhttps() {
            return jsonhttps;
        }

        /**
         * Sets the value of the jsonhttps property.
         * 
         * @param value
         *     allowed object is
         *     {@link Jsonserver }
         *     
         */
        public void setJsonhttps(Jsonserver value) {
            this.jsonhttps = value;
        }

        /**
         * Gets the value of the xmlhttp property.
         * 
         * @return
         *     possible object is
         *     {@link Xmlserver }
         *     
         */
        public Xmlserver getXmlhttp() {
            return xmlhttp;
        }

        /**
         * Sets the value of the xmlhttp property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xmlserver }
         *     
         */
        public void setXmlhttp(Xmlserver value) {
            this.xmlhttp = value;
        }

        /**
         * Gets the value of the xmlhttps property.
         * 
         * @return
         *     possible object is
         *     {@link Xmlserver }
         *     
         */
        public Xmlserver getXmlhttps() {
            return xmlhttps;
        }

        /**
         * Sets the value of the xmlhttps property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xmlserver }
         *     
         */
        public void setXmlhttps(Xmlserver value) {
            this.xmlhttps = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}parameter" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameter"
    })
    public static class Parameters {

        protected List<Parameter> parameter;

        /**
         * Gets the value of the parameter property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parameter property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParameter().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Parameter }
         * 
         * 
         */
        public List<Parameter> getParameter() {
            if (parameter == null) {
                parameter = new ArrayList<Parameter>();
            }
            return this.parameter;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}pdf"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}csv"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}html"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xls"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xml"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}rtf"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}text"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}pptx"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}xlsx"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}docx"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}odt"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}ods"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}json"/>
     *         &lt;element ref="{urn:rebelo.reports.core.parse.pojo}print"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pdf",
        "csv",
        "html",
        "xls",
        "xml",
        "rtf",
        "text",
        "pptx",
        "xlsx",
        "docx",
        "odt",
        "ods",
        "json",
        "print"
    })
    public static class Reporttype {

        protected Pdf pdf;
        protected Csv csv;
        protected Html html;
        protected Xls xls;
        protected Xml xml;
        protected Rtf rtf;
        protected Text text;
        protected Pptx pptx;
        protected Xlsx xlsx;
        protected Docx docx;
        protected Odt odt;
        protected Ods ods;
        protected Json json;
        protected Print print;

        /**
         * Gets the value of the pdf property.
         * 
         * @return
         *     possible object is
         *     {@link Pdf }
         *     
         */
        public Pdf getPdf() {
            return pdf;
        }

        /**
         * Sets the value of the pdf property.
         * 
         * @param value
         *     allowed object is
         *     {@link Pdf }
         *     
         */
        public void setPdf(Pdf value) {
            this.pdf = value;
        }

        /**
         * Gets the value of the csv property.
         * 
         * @return
         *     possible object is
         *     {@link Csv }
         *     
         */
        public Csv getCsv() {
            return csv;
        }

        /**
         * Sets the value of the csv property.
         * 
         * @param value
         *     allowed object is
         *     {@link Csv }
         *     
         */
        public void setCsv(Csv value) {
            this.csv = value;
        }

        /**
         * Gets the value of the html property.
         * 
         * @return
         *     possible object is
         *     {@link Html }
         *     
         */
        public Html getHtml() {
            return html;
        }

        /**
         * Sets the value of the html property.
         * 
         * @param value
         *     allowed object is
         *     {@link Html }
         *     
         */
        public void setHtml(Html value) {
            this.html = value;
        }

        /**
         * Gets the value of the xls property.
         * 
         * @return
         *     possible object is
         *     {@link Xls }
         *     
         */
        public Xls getXls() {
            return xls;
        }

        /**
         * Sets the value of the xls property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xls }
         *     
         */
        public void setXls(Xls value) {
            this.xls = value;
        }

        /**
         * Gets the value of the xml property.
         * 
         * @return
         *     possible object is
         *     {@link Xml }
         *     
         */
        public Xml getXml() {
            return xml;
        }

        /**
         * Sets the value of the xml property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xml }
         *     
         */
        public void setXml(Xml value) {
            this.xml = value;
        }

        /**
         * Gets the value of the rtf property.
         * 
         * @return
         *     possible object is
         *     {@link Rtf }
         *     
         */
        public Rtf getRtf() {
            return rtf;
        }

        /**
         * Sets the value of the rtf property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rtf }
         *     
         */
        public void setRtf(Rtf value) {
            this.rtf = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link Text }
         *     
         */
        public Text getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link Text }
         *     
         */
        public void setText(Text value) {
            this.text = value;
        }

        /**
         * Gets the value of the pptx property.
         * 
         * @return
         *     possible object is
         *     {@link Pptx }
         *     
         */
        public Pptx getPptx() {
            return pptx;
        }

        /**
         * Sets the value of the pptx property.
         * 
         * @param value
         *     allowed object is
         *     {@link Pptx }
         *     
         */
        public void setPptx(Pptx value) {
            this.pptx = value;
        }

        /**
         * Gets the value of the xlsx property.
         * 
         * @return
         *     possible object is
         *     {@link Xlsx }
         *     
         */
        public Xlsx getXlsx() {
            return xlsx;
        }

        /**
         * Sets the value of the xlsx property.
         * 
         * @param value
         *     allowed object is
         *     {@link Xlsx }
         *     
         */
        public void setXlsx(Xlsx value) {
            this.xlsx = value;
        }

        /**
         * Gets the value of the docx property.
         * 
         * @return
         *     possible object is
         *     {@link Docx }
         *     
         */
        public Docx getDocx() {
            return docx;
        }

        /**
         * Sets the value of the docx property.
         * 
         * @param value
         *     allowed object is
         *     {@link Docx }
         *     
         */
        public void setDocx(Docx value) {
            this.docx = value;
        }

        /**
         * Gets the value of the odt property.
         * 
         * @return
         *     possible object is
         *     {@link Odt }
         *     
         */
        public Odt getOdt() {
            return odt;
        }

        /**
         * Sets the value of the odt property.
         * 
         * @param value
         *     allowed object is
         *     {@link Odt }
         *     
         */
        public void setOdt(Odt value) {
            this.odt = value;
        }

        /**
         * Gets the value of the ods property.
         * 
         * @return
         *     possible object is
         *     {@link Ods }
         *     
         */
        public Ods getOds() {
            return ods;
        }

        /**
         * Sets the value of the ods property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ods }
         *     
         */
        public void setOds(Ods value) {
            this.ods = value;
        }

        /**
         * Gets the value of the json property.
         * 
         * @return
         *     possible object is
         *     {@link Json }
         *     
         */
        public Json getJson() {
            return json;
        }

        /**
         * Sets the value of the json property.
         * 
         * @param value
         *     allowed object is
         *     {@link Json }
         *     
         */
        public void setJson(Json value) {
            this.json = value;
        }

        /**
         * Gets the value of the print property.
         * 
         * @return
         *     possible object is
         *     {@link Print }
         *     
         */
        public Print getPrint() {
            return print;
        }

        /**
         * Sets the value of the print property.
         * 
         * @param value
         *     allowed object is
         *     {@link Print }
         *     
         */
        public void setPrint(Print value) {
            this.print = value;
        }

    }

}
